vich_uploader:
    db_driver: orm
    mappings:
        foto_perfil:
            uri_prefix: '%app.path.foto_perfil%'
            upload_destination: '%kernel.project_dir%/public%app.path.foto_perfil%'
